spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        format_sql: true
        show_sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5431/ChatApp
    username: Tushar
    password: Tushar@123
    driver-class-name: org.postgresql.Driver
server:
  port: 8088
