spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
        format_sql: true
  datasource:
    url: jdbc:postgresql://pR90StILo0okm4lRfsdl7nofIt19RAYS-a.oregon-postgres.render.com:5432/chat_app123
    username: tushar
    password: pR90StILo0okm4lRfsdl7nofIt19RAYS
    driver-class-name: org.postgresql.Driver
server:
  port: 8088