spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        format_sql: true
        show_sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://pR90StILo0okm4lRfsdl7nofIt19RAYS@dpg-d19bmfidbo4c73d50t30-a.oregon-postgres.render.com:5432/chat_app123
    username: tushar
    password: pR90StILo0okm4lRfsdl7nofIt19RAYS
    driver-class-name: org.postgresql.Driver
server:
  port: 8088
