spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: tushar
    password: tushar
  sql:
    init:
      mode: always
      schema-locations: classpath:/data.sql
      continue-on-error: true

server:
  port: 8088
